(function($) {
  "use strict"; // Start of use strict

  // Smooth scrolling using jQuery easing
  $('a.js-scroll-trigger[href*="#"]:not([href="#"])').click(function() {
    if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') && location.hostname == this.hostname) {
      var target = $(this.hash);
      target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
      if (target.length) {
        $('html, body').animate({
          scrollTop: (target.offset().top)
        }, 1000, "easeInOutExpo");
        return false;
      }
    }
  });

  // Closes responsive menu when a scroll trigger link is clicked
  $('.js-scroll-trigger').click(function() {
    $('.navbar-collapse').collapse('hide');
  });

  // Activate scrollspy to add active class to navbar items on scroll
  $('body').scrollspy({
    target: '#sideNav'
  });

})(jQuery); // End of use strict

var data = [{"museum":"Bay Area Discovery Museum","city":"Sausalito","state":"California","what":"Weekly Q&As for parents and a series of workshops/activities centered on one of three areas of early childhood development – Talk & Play, Science & Math, or Body & Brain.","link":"https://bayareadiscoverymuseum.org/bringing-badm-to-you","age":"Early Childhood","tech":"Most of the videos are posted on Youtube and embedded into their website, so you can watch any of the Q&As or workshops from their website. The more recent Q&A videos do not use Youtube; they appear to be using a combination of Facebook Live and Zoom. It is possible to hold a Zoom meeting with multiple participants on both Facebook live and Youtube live, so I do not have a good guess as to why they switched to Facebook, especially because the embedding doesn't look quite as good.","time":"Workshops for kids are usually just a few (1-5) minutes long, while live video Q&As for parents are around 30 minutes. Q&As are weekly, and new workshops appear to be posted about every 2-3 days.","educators":"Virtual Purple Museum with live broadcasts every M,W,F; a list of at-home activities, some with videos, others just with activity sheets - lots of variety; and a list of external parent resources about mental health, reading, and more. The most effort seems to be being put into the broadcasts. Types of broadcasts include Story Time,  where an educator reads a book, Toddler Fun, activities for toddlers, Let's Get Creative, art activities about nature, Science is Everywhere, at-home science activities, and Meet the Virtual Museum Educators, which is exactly what it sounds like.","money":"No cost, but donation is encouraged.","notes":"All of the resources on the website are directed toward parents to do activities with their younger children or to learn teaching techniques on their own; this is not a place for kids to come learn on their own online."},
{"museum":"Boston Children's Museum","city":"Boston","state":"Massachusetts","what":"Daily emails with activities, video programming.","link":"https://www.bostonchildrensmuseum.org/learning-resources","age":"Different activities for all ages; written activities specify appopriate age group.","tech":"Videos on Youtube, not embedded in the website itself.","time":"Videos range from 1 to 15 minutes, most are around 10 minutes. Videos are posted at least daily.","educators":"Lots of different educators contributing to video programming, usually 1 educator per video but a lot of the videos involve children.","money":"No cost, but donation is encouraged.","notes":"None"},
{"museum":"Cayton Children's Museum","city":"Los Angeles","state":"California","what":"Video broadcasts with music, storytime, and art every weekday.","link":"https://caytonmuseum.org/","age":"Not specified; seems geared toward younger children.","tech":"Videos hosted on Youtube and embedded within website. Videos also streamed on Facebook Live. Written activities directly on website. ","time":"Videos are between 3 to 15 minutes long and they are posted every weekday.","educators":"1 educator per video, and 2-3 educators are making most of the videos. Each educator seems to have their own video series (i.e. yoga or music).","money":"No cost, but there is a pop-up asking for donations when you enter the site.","notes":"Videos have between 20 to 40 views."},
{"museum":"Children's Discovery Museum of San Jose","city":"San Jose","state":"California","what":"Virtual Purple Museum with live broadcasts every M,W,F; a list of at-home activities, some with videos, others just with activity sheets - lots of variety; and a list of external parent resources about mental health, reading, and more. The most effort seems to be being put into the broadcasts. Types of broadcasts include Story Time,  where an educator reads a book, Toddler Fun, activities for toddlers, Let's Get Creative, art activities about nature, Science is Everywhere, at-home science activities, and Meet the Virtual Museum Educators, which is exactly what it sounds like.","link":"https://www.cdm.org/virtual-museum/","age":"Not specified on website, but seems like generally for younger kids: some activities designed for toddlers, other more science-oriented activities could probably work for up to age 10","tech":"Broadcasts are streamed live on Facebook, then added to a Youtube video archive. At-home activities either have an accompanying video from a broadcast or an accompanying pdf worksheet for kids to fill out.","time":"Broadcasts are every MWF and range from 10 to 30 minutes.","educators":"Each broadcase series is taught by a different educator, and there are about 6 educators that regularly contribute to broadcasts.","money":"No cost, but donation is encouraged.","notes":"It's worth noting that the broadcasts are super frequent and seem like they took a lot of effort, but they don't have too many views on Youtube...all the videos I saw had less than 100 views, and most had less than 50, or even 20. Many of the activities and parent resources are links to outside sources."},
{"museum":"Children's Discovery Museum of the Desert","city":"Rancho Mirage","state":"California","what":"Weekly conversation starters, Story Time videos, and other video series such as Ready, Set, Grow!, Little Chefs, and Creative Tots","link":"https://cdmod.org/programs/discover-at-home/","age":"All ages, different age groups for different activities (i.e. there is a series Little Chefs and a series Home Cooking Junior)","tech":"Youtube videos embedded in website.","time":"Storytime is less than 10 minutes, done every Tuesday, Thursday, and Saturday. Other series such as are done weekly and video length depends on the series; usually around 8-10 minutes.","educators":"1 educator per video usually, sometimes 2, and different educators seem to focus on specific areas (i.e. cooking vs storytime) ","money":"No cost.","notes":"Another case of having a lot of videos and a lot of effort put in and not many views...most of the videos here have less than 5 views, and most have none. The videos are directed toward children."},
{"museum":"Children's Museum at La Habra","city":"La Habra","state":"California","what":"No virtual learning","link":"http://www.lhcm.org/349/Childrens-Museum","age":"0","tech":"0","time":"0","educators":"0","money":"0","notes":"0"},
{"museum":"Children's Museum at the Paso Robles Volunteer Firehouse","city":"Paso Robles","state":"California","what":"Some at-home activities posted on Facebook, but not much.","link":"http://www.pasokids.org/","age":"0","tech":"0","time":"0","educators":"0","money":"0","notes":"0"},
{"museum":"Children's Museum Indianapolis","city":"Indianapolis","state":"Indiana","what":"Written activities and a wide variety of video broadcasts, from storytime to more active outdoor activities to be done at home.","link":"https://www.childrensmuseum.org/museum-at-home","age":"Not specified; seems geared toward younger children.","tech":"Videos hosted on Youtube and embedded within website.","time":"Videos range from 1 to 25 minutes. Videos are posted daily. Written activities appear to be posted weekly, give or take a few days.","educators":"Lots of educators contributing to video content. 1 educator per video.","money":"No cost, but there is a pop-up asking for donations when you enter the site.","notes":"There is also a virtual intern class of around 15 interns."},
{"museum":"Children's Museum of Denver","city":"Denver","state":"Colorado","what":"Facebook group offering screen-free activities.","link":"https://www.mychildsmuseum.org/","age":"The Facebook group is private, so it isn't clear what the activities are.","tech":"Facebook group","time":"NA","educators":"NA","money":"No cost, but donation is encouraged.","notes":"None."},
{"museum":"Children's Museum of Houston","city":"Houston","state":"Texas","what":"Daily virtual activities, including videos by educators filmed at the museum. Also offering Tinkercad workshops which gives kids an intro to CAD that seems really engaging. ","link":"https://www.cmhouston.org/page/daily-virtual-learning-summary","age":"Activities for all ages; lots of more complicated and engaging activities for older children.","tech":"Facebook Live streams, Youtube videos hosted on Youtube, and usage of software for games (like Tinkercad). Some workshops need to be registered for on Zoho, a business software.","time":"Videos range from 2 to 20 minutes but most are around 8 minutes. There are multiple videos posted daily.","educators":"Lots of different educators. There is usually 1 per video but it seems like many are still at the museum filming there.","money":"No cost, but donation is encouraged.","notes":"The interactive workshops like Tinkercad seem both well-organized and really interesting. "},
{"museum":"Children's Museum of Sonoma County","city":"Santa Rosa","state":"California","what":"Weekly newsletter with at-home activities, daily social media posts with at-home activities, virtual video programming on Facebook and Youtube with series such as Storytime, and Virtual Art Adventures. Also an extensive PLAYology Playbook with at-home activities.","link":"https://www.cmosc.org/resources/","age":"Activities for all ages; ages specified for virtual programming activities.","tech":"Videos are not embedded directly within museum website; there are links to Facebook events or Youtube playlists. Activities without videos have directions and photos directly in the website.","time":"Videos are short, usually less than 5 minutes. Videos and activities are posted frequently, and there appears to be some sort of programming every day.","educators":"Not clear how many educators are participating; there is one educator who does all the storytime videos, but it isn't clear who is working on the rest of the programming.","money":"Sold $20 Museum on the go kits that sold out. For online resources, no cost but donation is encouraged.","notes":"This museum has had a blog with at-home programming since 2015."},
{"museum":"Children's Museum of Stockton","city":"Stockton","state":"California","what":"At-home crafts and songs. All virtual programming is short videos.","link":"https://www.childrensmuseumstockton.org/fun-stuff-on-video","age":"Not specified; seems geared toward younger children.","tech":"All Youtube videos embedded in museum website.","time":"Videos are short, usually around 2 minutes. Initially, videos were posted more frequently (a few videos per week), but are now becoming less frequent (1 every week or 2 weeks).","educators":"A couple different educators, also kids involved participating in crafts.","money":"No cost.","notes":"None"},
{"museum":"Discovery Place","city":"Charlotte","state":"North Carolina","what":"Stay At Home Science activities, some with video and some written activities.","link":"https://www.discoveryplace.org/stay-at-home-science","age":"Not specified, but there is a wide range of activities for different age groups.","tech":"Some written activities hosted directly on the website and Youtube videos embedded in the website.","time":"Videos range from 2 to 15 minutes and are posted very frequently, almost every day.","educators":"There are several different educators contributing to video programming, at least 5.","money":"No cost, but there is a pop-up asking for donations when you enter the site.","notes":"None"},
{"museum":"Exploratorium","city":"San Francisco","state":"California","what":"Lots of online activities that are actually interactive, including apps and games.","link":"https://www.exploratorium.edu/explore","age":"Different activities for all ages; not specified for each activity.","tech":"Videos hosted directly on website, not on Youtube. Apps available for download. Games hosted directly on website.","time":"Lenght of activity varies, and it is unclear how regularly content is updates.","educators":"NA","money":"No cost for most of the content, but there is some content exclusively for members.","notes":"None"},
{"museum":"Habitot Children's Museum","city":"Berkeley","state":"California","what":"Newsletter with some at-home activities & parenting tips","link":"https://www.habitot.org/hab/newsletter/enews_archive/current_newsletter/current_enews_homepage1-15.html","age":"Not specified, but generally younger children.","tech":"Just a newsletter with links to external activities - no videos or content on website.","time":"NA","educators":"NA","money":"No cost, but donation is encouraged.","notes":"None"},
{"museum":"ImagineU Children's Museum","city":"Visalia","state":"California","what":"At-home activities like coloring pages; weekly story time and science lab broadcasts.","link":"https://www.imagineumuseum.org/","age":"Not specified; seems geared toward younger children.","tech":"Coloring pages are shared as pdf on their website. Video broadcasts cannot be found from their website! Video broadcasts can only be watched on Instagram.","time":"Videos posted weekly; videos are short, 2-5 minutes.","educators":"1 educator for each video, seems like 1-2 educators making most of the videos.","money":"No cost for virtual programming, but the museum did sell inspirational yard signs that sold out! https://www.imagineumuseum.org/yard-signs","notes":"I thought it was weird at first to have all the videos on Instagram instead of a more accessible platform like youtube, but most of the videos had between 200 to 500 views, which is a lot more than any of the Youtube videos from other museums."},
{"museum":"Kern Country Museum (Lori Brock Discovery Center)","city":"Bakersfield","state":"California","what":"No virtual programming","link":"https://kerncountymuseum.org/","age":"0","tech":"0","time":"0","educators":"0","money":"0","notes":"0"},
{"museum":"Kidspace Children's Museum","city":"Pasadena","state":"California","what":"At-home activities, videos, and blogs about different topics like animals. Also a virtual Rosebud parade.","link":"https://www.kidspacemuseum.org/events/home-learning-resources","age":"Different activities for all ages; not specified for each activity.","tech":"Most at-home activities and blogs do not have an accompanying video and are just text and photos within the website. Videos are hosted on Youtube and some are embedded within the website.","time":"Vidoes are short, around 5 minutes. Only a few videos are actually shown on the website, but on Youtube they appear to be posted about every other day.","educators":"1 educator for each video. Around 3 educators making most of the video content. ","money":"No cost, but donation is encouraged.","notes":"Some videos are embedded into the website, while others are just on the Youtube channel. The ones on the website have 100-500 views, while those just on the Youtube channel have 0-50."},
{"museum":"Kidzone Museum","city":"Truckee","state":"California","what":"Content such as videos, blogs, and at-home activities from external sites approved by museum staff.","link":"https://kidzonemuseum.org/kidzoneathome/","age":"All ages","tech":"Links to external sites; not much of the content is on the actual museum website.","time":"Length of activity varies and it is not clear how often activities are updated.","educators":"NA","money":"No cost, but donation is encouraged.","notes":"They are providing KidZone@Home kits to under-served families and you can donate to provide a kit for a family."},
{"museum":"Kohl Children's Museum","city":"Chicago","state":"Illinois","what":"Weekly Facebook Live broadcasts and Youtube at-home activities. Structured themes each week such as Water Works and Adventures in Art.","link":"https://www.kohlchildrensmuseum.org/temporary-exhibits/kohl-kids/","age":"Younger children, not specified.","tech":"Facebook Live streams hosted on Facebook and Youtube videos hosted on Youtube, not embedded in website.","time":"There are videos every weekday, ranging from 2 to 25 minutes.","educators":"There are several different educators contributing to video programming, at least 5.","money":"No cost, but donation is encouraged.","notes":"They have videos in English and Spanish!"},
{"museum":"Liberty Science Center","city":"Jersey City","state":"New Jersey","what":"Daily Facebook Live streams with animals, science, and more.","link":"https://lsc.org/education/lsc-in-the-house","age":"Activities for all ages; lots of more complicated science-related videos for older children.","tech":"Facebook Live streams that are posted on Youtube afterwards and embedded on the museum website.","time":"Videos are streamed daily and they are long - the planetarium ones are about an hour long.","educators":"There are at least 4 different educators contributing to video programming and each educator seems to work on a different topic (planetarium vs animals).","money":"No cost.","notes":"Some videos have close to 1000 views!"},
{"museum":"Madison Children's Museum","city":"Madison","state":"Wisconsin","what":"Videos of animals and activities on Facebook and Youtube and articles on blog.","link":"https://madisonchildrensmuseum.org/programs-and-events/mcmathome/","age":"Young children, and there is an explanation on their website that the activities are geared toward young children since there are less online learning tools available for your children.","tech":"Most content is not on the museum website itself; they provide one embedded Youtube video, as well as links to their Youtube channel, Facebook, and Instagram.","time":"Videos are between 2 and 20 minutes and are posted daily.","educators":"There are 3-4 different educators contributing to video content.","money":"No cost.","notes":"Videos have 0 to 20 views."},
{"museum":"Minnesota Children's Museum","city":"St Paul","state":"Minnesota","what":"Tips geared toward parents and at-home activities from external sources that are educator-approved. Many of these activities are interactive and seem engaging to kids on the computer.","link":"https://mcm.org/parent-resources/","age":"All ages","tech":"Activities are mostly just links to external sources.","time":"Length of activity varies, and it is not clear exactly how often content is updated. Blog has activities almost daily.","educators":"It is not clear how many educators are contributing because there is not video programming.","money":"No cost, but donation is encouraged.","notes":"A lot of the external activities seem engaging and interactive."},
{"museum":"Monterey Youth Museum","city":"Monterey","state":"California","what":"No virtual learning","link":"https://mymuseum.org/","age":"0","tech":"0","time":"0","educators":"0","money":"0","notes":"0"},
{"museum":"MOXI, The Wolf Museum of Exploration + Innovation","city":"Santa Barbara","state":"California","what":"At-home activities, available on website but also posted on Facebook and Instagram. Mostly video content but there are some written activities without videos.","link":"http://www.moxi.org/athome","age":"All ages, but weekly activities geared specifically toward toddlers.","tech":"Videos hosted externally on vimeo.","time":"Videos are short, often less than a minute, and the content is not regularly updated.","educators":"1 educator per video, seems like 2-3 educators are making most of the videos.","money":"No cost, but there is a pop-up asking for donations when you enter the site.","notes":"None"},
{"museum":"Museum of Science and Industry","city":"Chicago","state":"Illinois","what":"Science at home informational videos, games, and activities. ","link":"https://www.msichicago.org/science-at-home/","age":"Older children, not specified.","tech":"Games and activities are hosted directly on website, while videos are posted on Youtube and embedded in the website.","time":"Videos are longer, 5 to 30 minutes, and it is not clear how regularly activities are posted.","educators":"Videos are more informational than instructional, featuring science topics delivered documentary-style rather than from an educator.","money":"No cost.","notes":"None."},
{"museum":"Pennypickle's Workshop, Temecula Children's Museum","city":"Temecula","state":"California","what":"No virtual programming","link":"http://www.pennypickles.org/news.html","age":"0","tech":"0","time":"0","educators":"0","money":"0","notes":"0"},
{"museum":"Pittsburgh Children's Museum","city":"Pittsburgh","state":"Pennsylvania","what":"Video singalongs, crafts, and outdoor activities.","link":"https://pittsburghkids.org/museumathome","age":"Younger children, not specified.","tech":"Videos hosted on Youtube and embedded within website.","time":"Videos are short, 2 to 5 minutes, and videos are posted very frequently, almost daily.","educators":"1 educator per video, and it appears that there are 1-2 educators making most of the video programming.","money":"No cost.","notes":"They are also having a Great Night In with celebrity appearences, a VIP Q&A, and a spaghetti dinner for $400. "},
{"museum":"Please Touch Museum","city":"Philadelphia","state":"Pennsylvania","what":"No virtual programming","link":"https://www.pleasetouchmuseum.org/","age":"0","tech":"0","time":"0","educators":"0","money":"0","notes":"0"},
{"museum":"Port Discovery Children's Museum","city":"Baltimore","state":"Maryland","what":"Parenting tips and resources, including many written activities related to art and music. Also offers weekly Pop Up Play Time with music and games. ","link":"https://www.portdiscovery.org/visit/parenting-tips-resources?parenting-tips-resources=","age":"Younger children, not specified.","tech":"Facebook Live streams hosted on Facebook and Youtube videos hosted on Youtube and embedded in website.","time":"Videos are about 10 minutes long and streamed weekly.","educators":"1 educator is doing all of the video programming.","money":"No cost, but donation is encouraged.","notes":"None"},
{"museum":"Pretend City Children's Museum","city":"Irvine","state":"California","what":"Play at Home: Storytime and at-home activity videos directed toward kids.","link":"https://www.pretendcity.org/play-home/","age":"All ages, different age groups for different activities and they are specified in the activity description.","tech":"Mostly Youtube videos embedded in website; some Facebook Live activities and Zoom webinars.","time":"Storytime and activity videos are short: 1-10 minutes. Not sure about Facebook Live videos or Zoom webinars, or how often storytime videos are posted.","educators":"1 educator is in each activity or storytime video, sometimes with another child. It seems like one educator is doing most of the videos.","money":"No cost.","notes":"The layout of the activities is really nice, and the videos are short and engaging; also nice that they specify ages for each activity."},
{"museum":"Redwood Discovery Museum","city":"Eureka","state":"California","what":"No virtual programming","link":"https://www.discovery-museum.org/","age":"0","tech":"0","time":"0","educators":"0","money":"0","notes":"0"},
{"museum":"Sacramento Children's Museum","city":"Sacramento","state":"California","what":"No virtual learning","link":"https://sackids.org/hours-admission/coronavirus-precautions","age":"0","tech":"0","time":"0","educators":"0","money":"0","notes":"0"},
{"museum":"San Diego Children's Discovery Museum","city":"Escondido","state":"California","what":"Multiply daily broadcasts with at-home activities including storytime, art activities, music activities, and more.","link":"https://www.sdcdm.org/online-activities","age":"Not specified; seems more geared toward younger children but with at-home activities for different age groups.","tech":"Mostly using Youtube videos not embedded within site; using Facebook events to spread awareness of broadcasts; also putting videos on Facebook and Instagram.","time":"Videos are short, around 2 minutes on average.","educators":"1 educator for each video, seems like 3-4 different educators making videos.","money":"No cost.","notes":"None"},
{"museum":"San Luis Obispo Children's Museum","city":"San Luis Obispo","state":"California","what":"Video at-home activities, science tutorials, and advice for parents.","link":"https://www.slocm.org/busybox","age":"Not specified; seems geared toward younger children.","tech":"Videos hosted on Youtube and embedded within website.","time":"Videos are 2-5 minutes, and there are 4 videos total; it is not clear how regularly these videos are updated.","educators":"1 educator is making all of the videos.","money":"No cost.","notes":"They are also distributing Busy Boxes with crafts and instructions for children to complete at home."},
{"museum":"The New Children's Museum","city":"San Diego","state":"California","what":"Think Play Create From Home: weekly live zoom talks for caregivers, toddler programming on Fridays funded by scholarshare 529, and at-home activities such as coloring pages and virtual museum exhibit tours.","link":"https://thinkplaycreate.org/learn/creative-resources/","age":"Several toddler-specific activities; other at-home activities are for a wide range of ages, not specified but maybe up to around 13-14 years old with the more complicated crafts.","tech":"Using Zoom for weekly talks for givers, a private Facebook group for members-only event, and blog posts & other social media channels like instagram to share at-home activities.","time":"Weekly talks are , toddler time videos are usually just a few minutes.","educators":"1-2 educators for each weekly zoom call.","money":"Most of the Think Play Create From Home resources are available to anyone for free, but they are having a members-only event called Mass Creativity 2020 with virtual community workshops to inspire a new art exhibit. They are doing this in a private Facebook group for members. https://thinkplaycreate.org/learn/community-programs/mass-creativity/mass-creativity-2020/. They have also created a reNEWing Hope Fund to raise money for the museum to open after COVID.","notes":"The San Diego Padres are in several of the videos. Lots of videos directed toward kids, not just parents. Should be noted that this museum has had an online presence with at-home activities since before COVID, with blog posts as far back as 2016."},
{"museum":"The Strong","city":"Rochester","state":"New York","what":"Short stay-at-home activity prompts.","link":"https://www.museumofplay.org/education/play-at-home-activities","age":"Younger children, not specified.","tech":"Activities are written and displayed on website; there are no accompanying videos.","time":"Activites are short, just a few sentences, and it is not clear how often content is updated.","educators":"It is not clear how many educators are contributing because there is not video programming.","money":"No cost, but donation is encouraged.","notes":"None"}]
function addDataWith(museum, city, state, link, what, age, tech, time, educators, money, notes){
  var item = $('<div class="resume-item d-flex flex-column flex-md-row justify-content-between mb-5">')
  var content = $('<div class="resume-content">')
  var header = $('<h2 class="mb-0">')
  header.append(museum)
  var location = $('<div class="subheading text-primary">')
  location.append(city, ", ", state)
  var button = $('<a target="_blank" class="card-link btn btn-outline-info">')
  button.attr("href", link)
  button.append("Website")
  var what_h = $('<div class="h3 mb-3 text-secondary">')
  what_h.append("What programming are they offering?")
  var what_p = $("<p>")
  what_p.append(what)
  var age_h = $('<div class="h3 mb-3 text-secondary">')
  age_h.append("What age group is the programming for?")
  var age_p = $("<p>")
  age_p.append(age)
  var tech_h = $('<div class="h3 mb-3 text-secondary">')
  tech_h.append("What technology is being used?")
  var tech_p = $("<p>")
  tech_p.append(tech)
  var time_h = $('<div class="h3 mb-3 text-secondary">')
  time_h.append("How often & how long is the programming?")
  var time_p = $("<p>")
  time_p.append(time)
  var educators_h = $('<div class="h3 mb-3 text-secondary">')
  educators_h.append("How many educators are participating?")
  var educators_p = $("<p>")
  educators_p.append(educators)
  var money_h = $('<div class="h3 mb-3 text-secondary">')
  money_h.append("What is the cost?")
  var money_p = $("<p>")
  money_p.append(money)
  var notes_h = $('<div class="h3 mb-3 text-secondary">')
  notes_h.append("Other Notes")
  var notes_p = $("<p>")
  notes_p.append(notes)
  content.append(header, location, "<br>", button, "<br>", "<br>", what_h, what_p, age_h, age_p, tech_h, tech_p, time_h, time_p, educators_h, educators_p, money_h, money_p, notes_h, notes_p)
  item.append(content)
  $("#data-with").append(item)
}

function addDataWithout(museum, city, state, link){
  var item = $('<div class="resume-item d-flex flex-column flex-md-row justify-content-between mb-5">')
  var content = $('<div class="resume-content">')
  var header = $('<h3 class="mb-0">')
  header.append(museum)
  var location = $('<div class="subheading text-primary">')
  location.append(city, ", ", state)
  var button = $('<a target="_blank" class="card-link btn btn-outline-info">')
  button.attr("href", link)
  button.append("Website")
  content.append(header, location, "<br>", button, "<br>")
  item.append(content)
  $("#data-without").append(item)
}

function parseData(){
  for (i in data){
    var dict = data[i]
    var museum = dict["museum"]
    var city = dict["city"]
    var state = dict["state"]
    var link = dict["link"]
    var age = dict["age"]
    if (age == "0"){
      addDataWithout(museum, city, state, link)
    } else {
      addDataWith(museum, city, state, link, dict["what"], age, dict["tech"], dict["time"], dict["educators"], dict["money"], dict["notes"])
    }
    $("#experience").append(museum, city, state)
  }
}


$(document).ready(function() {
  parseData()
})
